dev-arm: fix --generate-dtb for ARM
Was failing with:

NameError: global name 'FdtNode' is not defined

The problem was introduced at: b459538a86b12e2d120e5f363b1e65293b29a9ee [formerly 75831ce5b7880b67c1aa2e0871ce16d5c01cadc7]

Change-Id: I7e2ce0e5311e7814229945b9f4e7318a8652dc1f
Reviewed-by: Andreas Sandberg <andreas.sandberg@arm.com>
Reviewed-on: https://gem5-review.googlesource.com/c/15875
Maintainer: Andreas Sandberg <andreas.sandberg@arm.com>

Former-commit-id: 34064c4647ff4b9e1675fa94347dfc0f7ded9e7c